"""Add AI logging tables

Revision ID: 157360752d35
Revises: 47e780517437
Create Date: 2025-11-25 15:13:53.169525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157360752d35'
down_revision = '47e780517437'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###