"""Add AI agent settings

Revision ID: d103f171c4c2
Revises: 157360752d35
Create Date: 2025-11-25 15:38:33.595121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd103f171c4c2'
down_revision = '157360752d35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###